Repository moul/sshportal, pull requests merged in 2020-07, with the labels that each got.

#184 chore: tell renovate to run go mod tidy
  .github/renovate.json
Labels: 🔍 Ready for Review

#183 Fix early closure of data stream.
  pkg/bastion/session.go
  pkg/bastion/ssh.go
Labels: ✅ Approved

#185 chore: small fix for build on windows
  testserver_unsupported.go
Labels: 🔍 Ready for Review

#168 fix: add more linters
  .golangci.yml
  pkg/bastion/acl.go
  pkg/bastion/acl_test.go
  pkg/bastion/dbinit.go
  pkg/bastion/session.go
  pkg/bastion/shell.go
  pkg/bastion/ssh.go
  pkg/dbmodels/dbmodels.go
  pkg/dbmodels/validator.go
Labels: 🔍 Ready for Review

#188 feat: host logging modes (disabled, input, everything)
  .gitattributes
  .gitignore
  CHANGELOG.md
  Makefile
  README.md
  go.mod
  go.sum
  main.go
  pkg/bastion/dbinit.go
  pkg/bastion/session.go
  pkg/bastion/shell.go
  pkg/bastion/ssh.go
  pkg/dbmodels/dbmodels.go
  pkg/dbmodels/validator.go
Labels: enhancement, help wanted, 🔍 Ready for Review

#196 chore: continue PR #194
  .gitignore
  go.sum
  main.go
  pkg/bastion/acl.go
  pkg/bastion/dbinit.go
  pkg/bastion/shell.go
  pkg/dbmodels/dbmodels.go
Labels: chore, 🔍 Ready for Review
