Repository moul/sshportal, pull requests merged in 2021-03, with the labels that each got.

#251 feat: Allow for update or removal of the invite token
  pkg/bastion/shell.go
Labels: enhancement

#248 feat: Allow removal by user for 'userkey rm'
  pkg/bastion/shell.go
  pkg/dbmodels/dbmodels.go
Labels: enhancement

#253 feat: Add postgres support
  pkg/dbmodels/dbmodels.go
Labels: enhancement

#254 feat: Allow user multiple keys with userkey create
  pkg/bastion/shell.go
Labels: enhancement

#249 fix: host inspect causes db errors with later operations
  pkg/bastion/shell.go
Labels: bug

#260 chore: maintenance
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  AUTHORS
  depaware.txt
  go.mod
  go.sum
  internal/tools/tools.go
  pkg/bastion/shell.go
  pkg/bastion/telnet.go
  pkg/dbmodels/dbmodels.go
  server.go
  testserver.go
Labels: chore

#262 feat: New Email validator
  pkg/bastion/shell.go
  pkg/utils/emailvalidator.go
  pkg/utils/emailvalidator_test.go
Labels: enhancement, go

#263 chore: bump CI's go version
  .github/workflows/ci.yml
Labels: chore
