Repository moul/sshportal, pull requests merged in 2023-05, with the labels that each got.

#466 chore: fix golangci-lint on CI
  .github/workflows/ci.yml
  .golangci.yml
  server.go
Labels: 🔍 Ready for Review

#416 Fix: typos
  README.md
Labels: 🔍 Ready for Review, ✅ Approved, Fix

#465 fix: change rand lib(math/rand => crypto/rand)
  pkg/bastion/dbinit.go
  pkg/bastion/shell.go
Labels: ✅ Approved
